from tkinter import *
def buttonBerechnenClick():
    Guthaben = int(entryGuthaben.get())
    Einsatz = int(entryEinsatz.get())
    neues_Guthaben = Guthaben-Einsatz
    neues_Guthaben_Anzeige = str(neues_Guthaben)
    labelneues_Guthaben2.config(text=neues_Guthaben_Anzeige)
tkFenster = Tk()
tkFenster.title('Spieleinsatz')
tkFenster.geometry('258x195')
labelGuthaben = Label(master=tkFenster, bg='#FFCFC9', text='Guthaben in €:')
labelGuthaben.place(x=54, y=24, width=100, height=27)
entryGuthaben = Entry(master=tkFenster, bg='white')
entryGuthaben.place(x=164, y=24, width=40, height=27)
labelEinsatz = Label(master=tkFenster, bg='#FFCFC9', text='Einsatz in €:')
labelEinsatz.place(x=54, y=64, width=100, height=27)
entryEinsatz = Entry(master=tkFenster, bg='white')
entryEinsatz.place(x=164, y=64, width=40, height=27)
buttonBerechnen = Button(master=tkFenster, bg='#FBD975', text='Berechnung', command=buttonBerechnenClick)
buttonBerechnen.place(x=54, y=104, width=100, height=27)
labelneues_Guthaben1 = Label(master=tkFenster, bg='#D5E88F', text='neues_Guthaben:')
labelneues_Guthaben1.place(x=54, y=144, width=100, height=27)
labelneues_Guthaben2 = Label(master=tkFenster, bg='gray', text='')
labelneues_Guthaben2.place(x=164, y=144, width=40, height=27)
tkFenster.mainloop()
